version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@commitlint/core"
    versions:
    - 12.0.0
    - 12.1.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.2.0
  - dependency-name: semantic-release
    versions:
    - 17.3.8
    - 17.3.9
  - dependency-name: typescript
    versions:
    - 3.9.8
  commit-message:
    prefix: "⬆"
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "⬆"
