name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: npm ci
        run: |
          npm ci
        env:
          CI: true

      - name: npm build & test
        run: |
          npm run build
          npm run test
        env:
          CI: true

      - name: npm semantic-release
        run: |
          npm run semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: 44210433+github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: 44210433+github-actions@users.noreply.github.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
